; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1_mini]
;platform = espressif8266
platform = espressif8266@2.6.3
board = d1_mini
framework = arduino
monitor_speed = 115200


; monitor_port = /dev/cu.usbserial-1450
; upload_port = /dev/cu.usbserial-1450
; monitor_filters = esp8266_exception_decoder, default
; build_type = debug

lib_deps = 
	contrem/arduino-timer@^2.1.0
	bblanchon/ArduinoJson @ ^6.17.3
	beegee-tokyo/DHT sensor library for ESPx@^1.17
	4-20ma/ModbusMaster@^2.0.1
	evert-arias/EasyButton @ ^2.0.1
	bodmer/TJpg_Decoder @ ^1.0.7
	knolleary/PubSubClient @ ^2.8
